# Generated by Django 6.0 on 2025-12-18 14:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('numparcelle', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('usage', models.CharField(max_length=100)),
                ('superficie', models.FloatField()),
                ('proprietaire', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
